add_newline = true

scan_timeout = 10

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[battery]
full_symbol = "🔋 "
charging_symbol = "⚡️ "
discharging_symbol = "💀 "

[aws]
disabled = true
format = 'on [$symbol($profile )(\($region\) )]($style)'
symbol = "🅰 "

[aws.region_aliases]
ap-northeast = "jp"
ap-southeast-2 = "au"
us-east-1 = "va"

[package]
disabled = false
